image: code0987/android-ci:latest

before_script:
  - git config user.email 'devbot@ilusons.com'
  - git config user.name 'Dev Bot'

  - git submodule update --init --recursive
  - git submodule update --recursive --remote

  - export GPG_TTY=/dev/console
  - echo "$DEVBOT_PRIVATE_KEY" | gpg --batch --import
  - git secret reveal

  - npm install
  - export GRADLE_USER_HOME=`pwd`./src/.gradle
  - chmod +x ./src/gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ./src/.gradle/
    - ./src/build/
    - ./src/app/build/

stages:
  - publish

publish:
  stage: publish
  only:
    - master
  script:
    - npx semantic-release
