name: Android CI

on:
  push:
    branches:
      - none

jobs:

  android-ci:
    runs-on: ubuntu-latest
    container: code0987/android-ci:latest

    steps:
    - uses: actions/checkout@v1

    - name: test
      run: |
        # Keys
        ## GPG
        export GPG_TTY=/dev/console
        echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        git secret reveal
        ## SSH
        'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "StrictHostKeyChecking no" >> ~/.ssh/config 
        echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config

        # Setup
        npm install
        export GRADLE_USER_HOME=`pwd`./src/.gradle
        chmod +x ./src/gradlew

        ./src/gradlew -p ./src bundleDebug
